baseURL = "https://blog.osismpksmaniwa.web.id/"
title   = "OSISMPK SMANIWA Board Pages"

DefaultContentLanguage = "en"

theme = "hello-friend-ng"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

rssLimit  = 20  # Maximum number of items in the RSS feed.
copyright = "this word is created by osismpksmaniwa. Further infos contact Administrative Authorities" # This message is only used by the RSS template.

googleAnalytics = "UA-68615481-5"
disqusShortname = "osismpk-blogs"

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpored = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = true
enableEmoji     = false
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[permalinks]
  posts = "/post/:year/:month/:title/"

[author]
  name = "Content Creator Authorities"

[blackfriday]
  hrefTargetBlank = true

[taxonomies]
  tag      = "tags"
  category = ""

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Nice theme for homepages and blogs"
  keywords = ""
  images = [""]

  homeSubtitle = "Students Creative Hub."

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  gitUrl = "https://github.com/osismpksmaniwa/blog.git"

  # Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
  customCSS = []
  customJS  = []

  # Toggle this option need to rebuild SCSS, requires extended version of Hugo
  justifyContent = true  # Set "text-align: justify" to .content.

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"
  themeColor = "#252627"

  [params.logo]
    logoText     = "$ cd /home/"
    logoHomeLink = "/"

  # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/omsmaniwa"

  [[params.social]]
    name = "email"
    url  = "mailto:vzrenggamani@osismpksmaniwa.web.id"

  [[params.social]]
    name = "github"
    url  = "https://github.com/osismpksmaniwa"

  [[params.social]]
    name = "Instagram"
    url  = "https://www.instagram.com/osismpksmaniwa"

  [[params.social]]
  name = "Youtube"
  url  = "https://www.youtube.com/c/osismpksmaniwa"

[languages]
  [languages.en]
    subtitle  = "Hello Friend NG Theme"
    weight    = 1
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

  [languages.fr]
    subtitle  = "Hello Friend NG Theme"
    weight    = 2
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "posts/"
